version: '3.2'
services:
  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - '27017:27017'
    env_file:
      - .env
  app:
    build: .
    container_name: app
    ports:
      - '3000:3000'
    env_file:
      - .env

